### ISSUE TITLE
Erreur de Map

### ISSUE THREAD

**Issue by liberodark** [StarLoco/StarLoco-Game#152]
Problème sur une map d'incarnam
![image](https://github.com/StarLoco/StarLoco-Game/assets/4238928/3d15c1f5-da25-4e85-b803-6947fcde9696)

```
19:06:25.943 [NioProcessor-7] ERROR o.s.l.d.data.login.AccountData - Error in org.starloco.locos.database.data.login.AccountData : null
java.lang.NullPointerException: null
        at org.starloco.locos.database.data.game.QuestProgressData.lambda$load$1(QuestProgressData.java:42) ~[game.jar:na]
        at org.starloco.locos.database.data.FunctionDAO.getData(FunctionDAO.java:82) ~[game.jar:na]
        at org.starloco.locos.database.data.game.QuestProgressData.load(QuestProgressData.java:32) ~[game.jar:na]
        at org.starloco.locos.database.data.login.PlayerData.lambda$loadByAccountId$3(PlayerData.java:269) ~[game.jar:na]
        at org.starloco.locos.database.data.FunctionDAO.getData(FunctionDAO.java:82) ~[game.jar:na]
        at org.starloco.locos.database.data.login.PlayerData.loadByAccountId(PlayerData.java:246) ~[game.jar:na]
        at org.starloco.locos.database.data.login.AccountData.lambda$load$0(AccountData.java:40) ~[game.jar:na]
        at org.starloco.locos.database.data.FunctionDAO.getData(FunctionDAO.java:92) ~[game.jar:na]
        at org.starloco.locos.database.data.login.AccountData.load(AccountData.java:30) ~[game.jar:na]
        at org.starloco.locos.game.world.World.ensureAccountLoaded(World.java:134) [game.jar:na]
        at org.starloco.locos.exchange.ExchangePacketHandler.parser(ExchangePacketHandler.java:64) [game.jar:na]
        at org.starloco.locos.exchange.ExchangeHandler.messageReceived(ExchangeHandler.java:19) [game.jar:na]
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854) [game.jar:na]
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [game.jar:na]
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [game.jar:na]
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [game.jar:na]
        at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109) [game.jar:na]
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [game.jar:na]
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535) [game.jar:na]
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714) [game.jar:na]
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668) [game.jar:na]
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657) [game.jar:na]
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [game.jar:na]
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121) [game.jar:na]
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [game.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_382]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_382]
        at java.lang.Thread.run(Thread.java:750) [na:1.8.0_382]
19:06:26.147 [NioProcessor-3] INFO  org.starloco.locos.game.world.World - The player Liberodark come to connect.
19:06:26.147 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark <-- AS2
19:06:26.147 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Rx0
19:06:26.147 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> ASK|2|Liberodark|16|10|0|100|-1|-1|-1|10~181~1~~;11~374~2~~;12~16e~1~~;19~1af4~1~~;1a~375~1~~;1b~372~1~~;d~17f~1~~;e~180~2~~;f~74e~2~~;
19:06:26.147 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> ZS0
19:06:26.147 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> cC+*#%!pi$:?^
19:06:26.147 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> al|0;0|512;1|1;0|513;1|2;0|514;1|3;0|515;2|4;0|5;0|6;0|7;0|8;0|9;0|10;0|11;0|12;0|13;0|14;0|15;0|16;0|17;0|18;0|19;0|20;0|21;0|22;0|23;0|536;0|25;0|26;0|27;0|28;0|29;0|30;0|31;0|32;0|33;0|34;0|35;0|37;1|38;0|39;0|41;0|42;0|43;1|44;1|45;1|46;1|47;1|48;1|49;1|50;1|51;1|53;2|54;0|55;0|56;0|57;0|59;1|61;2|62;0|63;0|64;0|65;0|66;0|67;0|68;0|69;0|70;0|71;0|72;2|73;1|74;0|75;2|76;0|77;0|78;0|79;0|80;0|81;0|82;0|83;0|84;0|85;0|86;0|87;0|88;0|89;0|91;0|92;0|93;0|94;0|95;0|96;0|97;0|98;0|99;0|100;0|101;0|102;0|103;0|105;0|106;0|107;0|108;0|109;0|110;0|111;0|112;0|113;0|114;0|115;0|116;0|117;0|118;0|119;0|120;0|121;0|122;0|123;0|124;0|125;0|126;0|127;0|128;0|129;0|130;0|131;0|132;0|133;0|134;0|135;0|136;0|137;0|138;0|139;0|140;0|141;0|143;0|144;0|145;0|146;0|147;0|148;0|149;0|150;0|151;0|152;0|153;0|154;0|155;0|156;0|157;0|158;0|159;0|161;0|162;0|163;0|164;0|165;0|166;0|167;0|168;0|169;0|170;0|171;0|173;0|174;0|175;0|177;0|178;0|179;0|180;0|181;0|182;0|200;0|201;0|202;0|203;0|204;0|205;0|206;0|207;0|208;0|209;0|210;0|211;0|212;0|213;0|214;0|215;0|216;0|217;0|218;0|219;0|220;0|221;0|222;0|223;0|224;0|225;0|226;0|227;0|228;0|229;0|230;0|231;0|232;0|233;0|234;0|235;0|236;0|243;0|244;0|245;0|246;0|247;0|248;0|249;0|250;0|251;0|252;0|253;0|254;0|255;0|256;0|257;0|258;0|259;0|260;0|261;0|266;0|267;0|268;0|269;0|270;0|271;0|272;0|273;0|274;0|275;0|276;0|277;0|278;0|279;1|280;2|284;0|285;0|286;0|287;0|288;0|289;0|290;0|291;0|292;0|293;0|294;0|295;0|296;0|297;0|298;0|299;0|300;0|301;0|302;0|303;0|304;0|306;0|307;0|308;0|309;0|310;0|311;0|312;0|313;0|314;0|315;0|316;0|317;0|318;0|319;0|320;0|321;0|322;0|323;0|324;0|325;0|326;0|327;0|328;0|329;0|330;0|331;0|332;0|333;0|334;0|335;0|336;0|337;1|338;2|339;0|440;0|441;0|442;0|443;0|444;0|445;0|446;0|447;0|448;0|449;0|450;0|451;0|452;0|453;0|454;0|455;0|457;0|459;0|460;0|461;0|462;0|463;0|464;0|465;0|466;0|467;0|468;0|469;0|470;0|471;0|472;0|474;0|476;0|477;0|478;0|479;0|480;0|481;0|482;0|483;0|484;0|485;0|486;0|487;0|488;0|490;0|491;0|492;0|493;0|494;0|495;0|496;0|497;0|498;0|499;0|500;0|501;0|502;2|503;2|504;2|505;2|506;2|507;2|508;2|509;2|1021;0|510;2|511;2|1023;0
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> eL-2147483648|0
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> AR6bk
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Ow10|10310
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> FO+
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> SL192~1~5;193~1~3;195~1~e;198~1~4;182~1~6;183~5~1;200~1~2
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Im189
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Im0152;2023~10~10~19~03~82.64.11.31
19:06:26.148 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Im0153;82.64.11.31
19:06:26.150 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> cs<font color='#B9121B'>Bienvenue sur StarLoco !</font>
19:06:26.150 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Im116;<b>Server</b>~Vous pouvez dès à présent voter, <b><a href='#YOUR_SITE'>cliquez ici</a></b> !
19:06:26.150 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> ILS2000
19:06:26.158 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark <-- Af
19:06:26.158 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Af1|1|1|1|601
19:06:26.196 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark <-- GC1
19:06:26.196 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> GCK|1|Liberodark
19:06:26.197 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> Ow10|10310
19:06:26.197 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> As88341,75000,91000|16389|1|5|0~0,0,1,0,0,0|125,125|9240,10000|79|100|6,0,0,0,6|3,0,0,0,3|62,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|1,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|0,0,0,0,0|
19:06:26.197 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> GDM|2196|0706131721|5677365c6667294d29524a42247c463d5e636a6a61423549663167544d6d264272462e2a4833614b757d4d787a3f32277e586761643e2d7b694c2f4f4c39287725324238267e24647d333c7054423a504f3369624f585a414f7d223a6b59545f6f5f423f4e6b24573f3d3a617b253235736d79592429605a796e574872323f4c5c75546c57696a3a612c224c6e30657535
19:06:26.197 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> fC0
19:06:26.440 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark <-- BD
19:06:26.440 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> BD2023|9|10
19:06:26.441 [NioProcessor-3] TRACE org.starloco.locos.game.world.World - Liberodark --> BT1696961186440
19:06:26.473 [NioProcessor-4] INFO  org.starloco.locos.game.world.World - Session 3 created
19:06:26.474 [NioProcessor-4] INFO  org.starloco.locos.game.world.World - Session 3 opened
19:06:26.474 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  --> HG
19:06:26.498 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  <-- AT8
19:06:26.499 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  --> ATK0
19:06:26.523 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  <-- Ak0
19:06:26.527 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  <-- AV
19:06:26.527 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  --> AV0
19:06:26.557 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  <-- Agfr
19:06:26.565 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  <-- AL
19:06:26.565 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  --> ALK86400000|0
19:06:26.579 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  <-- Af
19:06:26.579 [NioProcessor-4] TRACE org.starloco.locos.game.world.World -  --> Af1|1|1|1|601
```

**Comment by liberodark** [comment]
Fixed by SWF
