### ISSUE TITLE
Parler au Maitre du Dongeon d'Incarnam

### ISSUE THREAD

**Issue by liberodark** [StarLoco/StarLoco-Game#79]
Bonjour,

Le game crash (déconnexion du joueur) lors que l'ont parle au Maitre du Dongeon d'Incarnam.

Version : 1.0.3

![image](https://github.com/StarLoco/StarLoco-Game/assets/4238928/3226e80c-8f55-404c-b74a-f2f484ae0a7e)

```
13:00:48.959 [NioProcessor-2] ERROR org.starloco.locos.game.world.World - Exception connexion client : 
java.lang.RuntimeException: org.classdump.luna.exec.CallException: org.classdump.luna.runtime.IllegalOperationAttemptException: scripts/./data/npcs/dungeons/886_Ma'ster_Donge.lua:63: attempt to index a nil value
	at org.starloco.locos.script.ScriptVM.call(ScriptVM.java:123) ~[game.jar:na]
	at org.starloco.locos.entity.npc.NpcTemplate.onDialog(NpcTemplate.java:138) ~[game.jar:na]
	at org.starloco.locos.entity.npc.NpcTemplate.onCreateDialog(NpcTemplate.java:129) ~[game.jar:na]
	at org.starloco.locos.entity.npc.Npc.onCreateDialog(Npc.java:53) ~[game.jar:na]
	at org.starloco.locos.game.GameClient.npcCreateDialog(GameClient.java:1328) ~[game.jar:na]
	at org.starloco.locos.game.GameClient.parseDialogPacket(GameClient.java:1289) ~[game.jar:na]
	at org.starloco.locos.game.GameClient.parsePacket(GameClient.java:171) ~[game.jar:na]
	at org.starloco.locos.game.GameHandler.messageReceived(GameHandler.java:46) ~[game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:854) ~[game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [game.jar:na]
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:405) [game.jar:na]
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:235) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [game.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [game.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121) [game.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [game.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_382]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_382]
Caused by: org.classdump.luna.exec.CallException: org.classdump.luna.runtime.IllegalOperationAttemptException: scripts/./data/npcs/dungeons/886_Ma'ster_Donge.lua:63: attempt to index a nil value
	at org.classdump.luna.exec.DirectCallExecutor$Result.get(DirectCallExecutor.java:351) ~[game.jar:na]
	at org.classdump.luna.exec.DirectCallExecutor.execute(DirectCallExecutor.java:140) ~[game.jar:na]
	at org.classdump.luna.exec.DirectCallExecutor.resume(DirectCallExecutor.java:262) ~[game.jar:na]
	at org.classdump.luna.exec.DirectCallExecutor.call(DirectCallExecutor.java:239) ~[game.jar:na]
	at org.starloco.locos.script.ScriptVM.call(ScriptVM.java:121) ~[game.jar:na]
	... 28 common frames omitted
Caused by: org.classdump.luna.runtime.IllegalOperationAttemptException: scripts/./data/npcs/dungeons/886_Ma'ster_Donge.lua:63: attempt to index a nil value
	at org.classdump.luna.runtime.Errors.illegalIndexAttempt(Errors.java:71) ~[game.jar:na]
	at org.classdump.luna.runtime.Dispatch.index(Dispatch.java:1377) ~[game.jar:na]
	at luna_dynamic.Data39$2.run(scripts/./data/npcs/dungeons/886_Ma'ster_Donge.lua:63) ~[na:na]
	at luna_dynamic.Data39$2.invoke(scripts/./data/npcs/dungeons/886_Ma'ster_Donge.lua) ~[na:na]
	at org.classdump.luna.runtime.AbstractFunction3.invoke(AbstractFunction3.java:68) ~[game.jar:na]
	at org.classdump.luna.runtime.Dispatch.mt_invoke(Dispatch.java:128) ~[game.jar:na]
	at org.classdump.luna.runtime.Dispatch.call(Dispatch.java:436) ~[game.jar:na]
	at org.classdump.luna.runtime.Coroutine$BootstrapResumable.resume(Coroutine.java:159) ~[game.jar:na]
	at org.classdump.luna.runtime.ResumeInfo.resume(ResumeInfo.java:35) ~[game.jar:na]
	at org.classdump.luna.runtime.Call$Resumer.continueCurrentCoroutine(Call.java:504) ~[game.jar:na]
	at org.classdump.luna.runtime.Call$Resumer.resume(Call.java:526) ~[game.jar:na]
	at org.classdump.luna.runtime.Call.resume(Call.java:160) ~[game.jar:na]
	at org.classdump.luna.runtime.Call.access$500(Call.java:36) ~[game.jar:na]
	at org.classdump.luna.runtime.Call$CallContinuation.resume(Call.java:319) ~[game.jar:na]
	at org.classdump.luna.exec.DirectCallExecutor.execute(DirectCallExecutor.java:121) ~[game.jar:na]
	... 31 common frames omitted
13:00:48.970 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection com.mysql.jdbc.JDBC4Connection@7b948d8f
13:00:48.981 [NioProcessor-2] INFO  org.starloco.locos.game.world.World - The player Liberodark come to disconnect.
13:00:48.981 [NioProcessor-2] ERROR org.starloco.locos.game.world.World - Exception connexion client : 
org.apache.mina.core.write.WriteToClosedSessionException: null
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.clearWriteRequestQueue(AbstractPollingIoProcessor.java:642) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeNow(AbstractPollingIoProcessor.java:594) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeSessions(AbstractPollingIoProcessor.java:564) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$800(AbstractPollingIoProcessor.java:67) [game.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1129) [game.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [game.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_382]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_382]
13:00:48.982 [NioProcessor-2] INFO  org.starloco.locos.game.world.World - Session 3 closed

```

**Comment by Diabu** [comment]
Crash fixed in master.
Someone still needs to work on the quest 198
